Update `imageio` to version `2.10.3`
AnacondaRecipes/imageio-feedstock pull request #14
Opened 2022-01-06 15:31 UTC by varlackc

`imageio` version `2.10.3`
1. check the upstream
    https://github.com/imageio/imageio/tree/v2.10.3

2. check the pinnings
    https://github.com/imageio/imageio/blob/v2.10.3/setup.py
    https://github.com/imageio/imageio/blob/v2.10.3/setup.cfg
    https://github.com/imageio/imageio/blob/v2.10.3/MANIFEST.in

3. check the changelogs
    https://github.com/imageio/imageio/blob/v2.10.3/CHANGELOG.md

4. additional research
    https://github.com/conda-forge/imageio-feedstock/issues

   There were no open issues mentioned in `conda-forge`

5. verify dev_url
    https://github.com/imageio/imageio

6. verify doc_url
    https://imageio.readthedocs.io

7. pip in the test section
8. veriy the test section
9. additional tests

In order to test the `imageio` package version `2.10.3` the folowing
command was used:
`conda build imageio-feedstock --test`
the test result was the following:
`All tests passed`

Based on the research findings and the test results we can conclude
that it is safe to update `imageio` to version `2.10.3`

2022-07-18 18:15 UTC, chenghlee requested changes

2022-07-18 18:15 UTC, chenghlee commented on recipe/meta.yaml
> +    - python >=3.7
Arch-specific packages should not use `>=3.x` in their `python` run constraints. Those bounds should be automatically generated by `conda build` based on the python version fed in from cbc.yaml.

2022-07-18 19:47 UTC, varlackc commented on recipe/meta.yaml
> +    - python >=3.7
The python restrictions have been modified.

2022-07-18 19:48 UTC, varlackc commented on recipe/meta.yaml
> +    - python
The python pinnings have been modified.

2022-07-19 08:05 UTC, tobijk approved these changes

2022-07-19 08:35 UTC, skupr-anaconda approved these changes

2022-07-19 15:55 UTC, chenghlee approved these changes

2022-07-25 21:36 UTC, merged